spring.profiles.active=dev
#\uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC5F0\uACB0 \uC815\uBCF4
#spring.datasource.driverClassName=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://localhost:3306/study_db
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy

# \uB85C\uCEEC DB
#spring.datasource.url=jdbc:log4jdbc:mariadb://localhost:3306/study_db
#spring.datasource.username=study_user
#spring.datasource.password=mariadb

#\uCFFC\uB9AC\uBB38\uC774 \uC788\uB294 mapper \uD30C\uC77C \uC704\uCE58 \uC9C0\uC815, classpath\uB294 resources \uD3F4\uB354\uB97C \uC758\uBBF8\uD568

# \uCEE4\uB125\uC158 \uC124\uC815
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.green.namuwiki

#\uD55C \uD30C\uC77C\uC758 \uC6A9\uB7C9\uC744 5MB\uB85C \uC124\uC815
spring.servlet.multipart.max-file-size=10MB
#\uD55C \uBC88\uC5D0 \uC5C5\uB85C\uB4DC\uB418\uB294 \uC6A9\uB7C9\uC744 5MB\uB85C \uC124\uC815
spring.servlet.multipart.max-request-size=10MB

# JWT \uC124\uC815
#jwt.secret=\uC2DC\uD06C\uB9BF \uD0A4
#jwt.access-token-expiration=1800000
#jwt.refresh-token-expiration=604800000

# Swagger
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/v3/api-docs

# \uCCA8\uBD80\uD30C\uC77C \uC800\uC7A5 \uC704\uCE58
#file.upload.dir=D:/01-STUDY/dev/upload/
# s3 \uC124\uC815\uC4F0
cloud.aws.active=false

# api prefix \uC124\uC815
server.servlet.context-path=/api
